[package]
name = "yarer"
version = "0.1.0"
authors = ["Davassi <gianluigi.davassi@gmail.com>"]
description = "Yarer is a Reverse Polish Notation expression resolver"
homepage = "https://github.com/davassi/Yarer"
edition = "2021"

[dependencies]
clap = { version = "4.3.21", features = ["derive"] }
regex = "1.9.1"
